# Generated by Django 6.0.3 on 2026-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
