# Generated by Django 6.0.3 on 2026-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0002_booking_is_active_booking_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='upcoming', max_length=10),
        ),
    ]
