# Generated by Django 6.0.3 on 2026-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bench',
            name='category',
        ),
        migrations.AddField(
            model_name='bench',
            name='IPN_VARIANT',
            field=models.CharField(choices=[('IPN-10', 'iPN-10'), ('IPN-12', 'iPN-12'), ('IPN-14', 'iPN-14'), ('IPN-15', 'iPN-15')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bench',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
