# Generated by Django 6.0.3 on 2026-03-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer1', 'Customer1'), ('customer2', 'Customer2'), ('customer3', 'Customer3'), ('manager', 'Manager')], max_length=30),
        ),
    ]
