# Generated by Django 6.0.3 on 2026-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor_1', 'Vendor_1'), ('vendor_2', 'Vendor_2'), ('vendor_3', 'Vendor_3'), ('manager', 'Manager')], max_length=30),
        ),
    ]
