# Generated by Django 6.0.3 on 2026-03-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('manager', 'Manager')], default='user', max_length=10),
        ),
    ]
